env:
  FLUTTER_VERSION: "3.32.5"
  ORAS_CACHE: /Users/agent/oras-cache

agents:
  queue: "macos"

cache:
  paths:
    - /Users/agent/oras-cache
  size: "20g"

steps:
  - label: ":package: Build flutter image"
    key: "build-flutter-image"
    command:
      - "./flutter-sdk-to-oci.sh"

  - label: ":rocket: Mount and verify flutter image"
    command:
      - "./mount-flutter-image.sh"
    depends_on: ["build-flutter-image"]
